//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help_Desk_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int ID { get; set; }
        public Nullable<int> parentID { get; set; }
        public Nullable<int> commonID { get; set; }
        public string fileName { get; set; }
        public string filePath { get; set; }
    
        public virtual KnowledgeFAQ KnowledgeFAQ { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
