//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help_Desk_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int ID { get; set; }
        public int refID { get; set; }
        public System.DateTime timeStamp { get; set; }
        public System.Guid userID { get; set; }
        public string text { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
