//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help_Desk_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalSettings
    {
        public System.Guid ID { get; set; }
        public int TicketSeeder { get; set; }
        public string TicketHeader { get; set; }
        public int TicketExpiryDays { get; set; }
        public int FAQsExpiryDays { get; set; }
        public int KBExpiryDays { get; set; }
        public bool TicketHeaderEnabled { get; set; }
    }
}
