//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help_Desk_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeFAQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KnowledgeFAQ()
        {
            this.Attachment = new HashSet<Attachment>();
            this.WordList = new HashSet<WordList>();
        }
    
        public int ID { get; set; }
        public System.DateTime dateComposed { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<System.DateTime> dateSubmitted { get; set; }
        public string headerText { get; set; }
        public string description { get; set; }
        public System.Guid originatorID { get; set; }
        public bool suggest { get; set; }
        public bool published { get; set; }
        public bool deleted { get; set; }
        public bool processed { get; set; }
        public string links { get; set; }
        public byte type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordList> WordList { get; set; }
    }
}
