//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help_Desk_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string body { get; set; }
        public bool sticky { get; set; }
        public bool published { get; set; }
        public bool deleted { get; set; }
        public Nullable<System.DateTime> publishedDate { get; set; }
        public System.Guid originatorID { get; set; }
        public System.DateTime creationDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
