//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Help_Desk_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Attachment = new HashSet<Attachment>();
            this.AuditTrail = new HashSet<AuditTrail>();
            this.WordList = new HashSet<WordList>();
        }
    
        public int ID { get; set; }
        public int ticketID { get; set; }
        public System.Guid originatorID { get; set; }
        public Nullable<System.Guid> responsibleID { get; set; }
        public System.DateTime dateComposed { get; set; }
        public Nullable<System.DateTime> expiryDate { get; set; }
        public Nullable<System.DateTime> dateCompleted { get; set; }
        public bool deleted { get; set; }
        public bool onhold { get; set; }
        public bool returned { get; set; }
        public string headerText { get; set; }
        public string description { get; set; }
        public string links { get; set; }
        public Nullable<System.DateTime> dateSubmitted { get; set; }
        public Nullable<System.DateTime> dateL1Release { get; set; }
        public Nullable<System.DateTime> dateL2Release { get; set; }
        public string reason { get; set; }
        public string adminComments { get; set; }
        public Nullable<int> sanityCheck { get; set; }
        public string summary { get; set; }
        public string report { get; set; }
        public Nullable<System.Guid> UserProfile_userID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTrail> AuditTrail { get; set; }
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
        public virtual UserProfile UserProfile2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WordList> WordList { get; set; }
    }
}
